pacakge: libs: classpath: compiling error
compilig error is as following
gnu_java_math_GMP.c:1134:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
         res = mpz_popcount (_this);
         ~~~~^~~~~~~~~~~~~~~~~~~~~~
gnu_java_math_GMP.c:1135:7: note: here
       default:
       ^~~~~~~
so the compiling option -Wno-error=implicit-fallthrough is added.

Signed-off-by: Hua Zhang <hua.zhang1974@hotmail.com>