package: libs: libmraa: fix compiling errors
There are some compiling errors as following:
/home/zhanghua/mydev/openwrt-test-32/build_dir/target-mipsel_mips32r6_musl/libmraa-0.8.0/src/javascript/mraajsJAVASCRIPT_wrap.cxx: In function 'SwigV8ReturnValue _wrap_I2c_read(const SwigV8Arguments&)':
/home/zhanghua/mydev/openwrt-test-32/build_dir/target-mipsel_mips32r6_musl/libmraa-0.8.0/src/javascript/mraajsJAVASCRIPT_wrap.cxx:7020:54: error: no matching function for call to 'New(char*, int&)'
     jsresult = node::Buffer::New((char*) arg2, result);

The old version is 0.8.0. It is too old and upgraded to 2.0.0

Signed-off-by: Hua Zhang <hua.zhang1974@hotmail.com>